### ISSUE TITLE
Unable to wrap FlexibleTextItem with other widgets

### ISSUE THREAD

**Issue by NikhilKukreja26** [miroslava-podybailo/flutter_sliver_header_delegate#4]
Hello,
I am using FlexibleTextItem but if text goes long i want to show some text and then dots.
But i can't wrap other widgets it doesn't have overflow property also.
Can you please add some property for text overflow
Thank you.

**Comment by miroslava-podybailo** [comment]
Hi :)  

Thanks for pointing this out! 
I've added some properties to FlexibleTextItem so now you can add overflow to your text. 

Please update the package version to 0.0.4 in your pubspec.yaml: 
`sliver_header_delegate: ^0.0.4`

If you need more customisable items you can provide `builder` in `FlexibleHeaderDelegate` and use `progress` value from it. And/or create a new issue or pull request. 

Thank you!

**Comment by NikhilKukreja26** [comment]
Thank you so much :)
