### ISSUE TITLE
type 'List<Widget?>' is not a subtype of type 'Iterable<Widget>' in type cast error

### ISSUE THREAD

**Issue by srcho8** [miroslava-podybailo/flutter_sliver_header_delegate#6]
hello i'm korean developer

i faced this problem. 

It appears to be due to the children property in the FlexibleHeaderDelegate.

I found that condition line 82 in FlexibleHeaderDelegate Class

like this:
children: [
                if (builder != null) builder!(context, progress),
                if (children != null)
                  ...children!.map((item) => item.transform(progress)).toList()
                      **as Iterable<Widget>**,
              ],

It was fine in previous versions of null-safety.

**Comment by mixable** [comment]
This also happens on my app. The following code change solved it for me:

```dart
              children: [
                if (builder != null) builder!(context, progress),
                if (children != null)
                  ...children!.map((item) => item.transform(progress) ?? item),
              ],
```

**Comment by srcho8** [comment]
> This also happens on my app. The following code change solved it for me:
> 
> ```dart
>               children: [
>                 if (builder != null) builder!(context, progress),
>                 if (children != null)
>                   ...children!.map((item) => item.transform(progress) ?? item),
>               ],
> ```

thank you!!

**Comment by MrFantuk** [comment]
Same problem, above solution didn't help. Any suggestions?

**Comment by miroslava-podybailo** [comment]
Thanks for creating this issue! 
I've just pushed a new version. Please update the package version to 0.0.5: 

`sliver_header_delegate: ^0.0.5`

Please let me know if it works for you

@srcho8 @mixable  @MrFantuk  ^^

**Comment by MrFantuk** [comment]
Works great! Thank you! 👍
