### ISSUE TITLE
actions are not accessible when backgroundColor is defined

### ISSUE THREAD

**Issue by mixable** [miroslava-podybailo/flutter_sliver_header_delegate#7]
The following example does not allow access to the IconButtons defined in `actions`, because a value is defined for `backgroundColor` (`const Color.fromRGBO(200, 150, 0, 1)`). This is also the case, if a global background color is defined for AppBar using ThemeData.

```dart
          SliverPersistentHeader(
            pinned: true,
            delegate: FlexibleHeaderDelegate(
              statusBarHeight: MediaQuery.of(context).padding.top,
              expandedHeight: 240,
              backgroundColor: const Color.fromRGBO(200, 150, 0, 1),
              actions: [
                IconButton(
                  icon: const Icon(Icons.search),
                  onPressed: () {},
                ),
                IconButton(
                  icon: const Icon(Icons.more_vert),
                  onPressed: () {},
                ),
              ],
              children: [
                FlexibleTextItem(
                  text: 'Mountains',
                  collapsedStyle: collapsedStyle,
                  expandedStyle: expandedStyle,
                  expandedAlignment: Alignment.bottomLeft,
                  collapsedAlignment: Alignment.center,
                  expandedPadding: padding,
                ),
              ],
            ),
          ),
```
The color covers all the contents of `AppBar`:

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-04-17 at 14 02 30](https://user-images.githubusercontent.com/5080095/115112433-dbadcf80-9f85-11eb-82b8-6032859e651c.png)

Changing the opacity of the color `Color.fromRGBO(200, 150, 0, 0.5)`, you can see the IconButtons in the background. They are still not clickable:

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-04-17 at 14 02 50](https://user-images.githubusercontent.com/5080095/115112457-eec09f80-9f85-11eb-9aeb-4b646532c932.png)

The reason for this is the order of the items in Stack defined in sliver_header_delegate.dart line 60. In the current version `Container` covers all actions in `AppBar`, because it is above the `AppBar`. The correct order is listed below. In this case,  `Container` is below `AppBar`:

```dart
      child: Stack(
        fit: StackFit.expand,
        children: [
          if (background != null) background.transform(progress)!,
          Container(
            height: visibleMainHeight,
            padding: EdgeInsets.only(top: statusBarHeight),
            color: backgroundColor ?? Theme.of(context).appBarTheme.color,
            child: Stack(
              fit: StackFit.expand,
              children: [
                if (builder != null) builder!(context, progress),
                if (children != null)
                  ...children!.map((item) => item.transform(progress)).toList()
                      as Iterable,
              ],
            ),
          ),
          AppBar(
            backgroundColor: Colors.transparent,
            actions: actions,
            leading: leading,
            title: title,
            elevation: 0,
          ),
        ],
      ),

```

**Comment by miroslava-podybailo** [comment]
Hey! 
I've just pushed a new version. Please update the package version to 0.0.5:

sliver_header_delegate: ^0.0.5

Thank you!

**Comment by callmejm** [comment]
@miroslava-podybailo I facing same issue, but my project is non null safety, how to resolve ?
